name: Build and Push Docker Image (Spark-TTS)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.actor }}/spark-tts
  VERSION: ${{ secrets.VERSION || '0.0.1' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and Export Cache
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --tag $IMAGE_NAME:$VERSION \
            --tag $IMAGE_NAME:latest \
            --output=type=docker \
            --file Dockerfile \
            .

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-cache
          path: /tmp/.buildx-cache
          retention-days: 7
